"""16개 테이블 초기 스키마

Revision ID: 939bc1d14754
Revises: 
Create Date: 2026-09-05 13:20:20.352727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy  # KNOWLEDGE_CHUNKS.embedding(VECTOR) 렌더링에 필요
from sqlalchemy.dialects import postgresql

# 이 마이그레이션에서 만드는 ENUM 타입 15종(명세서 v1.3 1절).
#   downgrade 시 테이블만 지우면 타입이 남아 재적용이 실패하므로 함께 정리한다.
ENUM_TYPE_NAMES = (
    "accommodation_type_enum",
    "bookable_unit_type_enum",
    "channel_enum",
    "sync_status_enum",
    "reservation_status_enum",
    "refund_status_enum",
    "financial_status_enum",
    "fee_type_enum",
    "task_status_enum",
    "inquiry_risk_level_enum",
    "action_risk_level_enum",
    "action_status_enum",
    "approval_status_enum",
    "document_type_enum",
    "renewal_trigger_type_enum",
)

# revision identifiers, used by Alembic.
revision: str = '939bc1d14754'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- 수동 추가 1: PostgreSQL 확장 (명세서 5절 1번) ---
    #   btree_gist: RESERVATIONS의 EXCLUDE 제약에서 property_id/room_id/bed_id
    #     같은 스칼라 컬럼을 GiST 인덱스로 다루기 위해 필요.
    #   vector(pgvector): KNOWLEDGE_CHUNKS.embedding용. 별도 벡터DB 서버
    #     (ChromaDB 등)는 도입하지 않는다.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('host_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('host_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('properties',
    sa.Column('property_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('accommodation_type', sa.Enum('URBAN_HOMESTAY', 'RURAL_HOMESTAY', 'HANOK', 'HOSTEL', 'LODGING_FACILITY', 'GENERAL_LODGING', name='accommodation_type_enum'), nullable=False),
    sa.Column('bookable_unit_type', sa.Enum('PROPERTY', 'ROOM', 'BED', name='bookable_unit_type_enum'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('base_price', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('lower_bound_price', sa.Integer(), nullable=True),
    sa.Column('checkin_time', sa.Time(), server_default=sa.text("'15:00'"), nullable=False),
    sa.Column('checkout_time', sa.Time(), server_default=sa.text("'11:00'"), nullable=False),
    sa.Column('weekday_adjustment_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('holiday_adjustment_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.host_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('property_id')
    )
    op.create_index('idx_properties_host', 'properties', ['host_id'], unique=False)
    op.create_table('channel_connections',
    sa.Column('connection_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.Enum('AIRBNB', 'BOOKING_COM', 'NAVER', name='channel_enum'), nullable=False),
    sa.Column('ical_url', sa.Text(), nullable=True),
    sa.Column('external_property_id', sa.String(length=100), nullable=True),
    sa.Column('sync_status', sa.Enum('SYNCING', 'SYNCED', 'FAILED', 'STALE', name='sync_status_enum'), server_default=sa.text("'SYNCING'"), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('connection_id'),
    sa.UniqueConstraint('connection_id', 'property_id', name='uq_channel_connection_property_ref'),
    sa.UniqueConstraint('property_id', 'channel', name='uq_property_channel')
    )
    op.create_index('idx_channel_connections_property', 'channel_connections', ['property_id'], unique=False)
    op.create_table('checklist_items',
    sa.Column('checklist_item_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('accommodation_type', sa.Enum('URBAN_HOMESTAY', 'RURAL_HOMESTAY', 'HANOK', 'HOSTEL', 'LODGING_FACILITY', 'GENERAL_LODGING', name='accommodation_type_enum'), nullable=False),
    sa.Column('item_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'INCOMPLETE'"), nullable=False),
    sa.Column('renewal_trigger_type', sa.Enum('NONE', 'EXPIRATION_BASED', 'EVENT_BASED', name='renewal_trigger_type_enum'), server_default=sa.text("'NONE'"), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(renewal_trigger_type = 'NONE' AND expiry_date IS NULL) OR (renewal_trigger_type = 'EXPIRATION_BASED' AND expiry_date IS NOT NULL) OR (renewal_trigger_type = 'EVENT_BASED')", name='ck_checklist_items_renewal_expiry'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('checklist_item_id')
    )
    op.create_index('idx_checklist_items_property', 'checklist_items', ['property_id'], unique=False)
    op.create_table('financial_configs',
    sa.Column('config_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_type', sa.Enum('SPLIT_FEE', 'SINGLE_FEE', name='fee_type_enum'), server_default=sa.text("'SINGLE_FEE'"), nullable=False),
    sa.Column('commission_rate', sa.Numeric(precision=5, scale=4), server_default=sa.text('0.1550'), nullable=False),
    sa.Column('fee_source', sa.String(length=50), server_default=sa.text("'system_default_2026'"), nullable=False),
    sa.Column('base_nightly_rate', sa.Integer(), nullable=True),
    sa.Column('vat_included', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_table('knowledge_chunks',
    sa.Column('chunk_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.Enum('HOUSE_RULE', 'POLICY', 'FAQ', name='document_type_enum'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index('idx_knowledge_chunks_property', 'knowledge_chunks', ['property_id'], unique=False)
    op.create_table('monthly_settlements',
    sa.Column('settlement_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('target_month', sa.CHAR(length=7), nullable=False),
    sa.Column('total_reservations', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('occupied_nights', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('occupancy_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('gross_revenue', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('channel_fee', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('net_payout', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('applied_commission_rate', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('settlement_id'),
    sa.UniqueConstraint('property_id', 'target_month', name='uq_settlement_property_month')
    )
    op.create_table('rooms',
    sa.Column('room_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id'),
    sa.UniqueConstraint('property_id', 'room_name', name='uq_property_room_name'),
    sa.UniqueConstraint('room_id', 'property_id', name='uq_room_property_ref')
    )
    op.create_index('idx_rooms_property', 'rooms', ['property_id'], unique=False)
    op.create_table('beds',
    sa.Column('bed_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=False),
    sa.Column('bed_label', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.room_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bed_id'),
    sa.UniqueConstraint('bed_id', 'room_id', name='uq_bed_room_ref'),
    sa.UniqueConstraint('room_id', 'bed_label', name='uq_room_bed_label')
    )
    op.create_index('idx_beds_room', 'beds', ['room_id'], unique=False)
    op.create_table('reservations',
    sa.Column('reservation_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('room_id', sa.BigInteger(), nullable=True),
    sa.Column('bed_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_connection_id', sa.BigInteger(), nullable=False),
    sa.Column('external_uid', sa.String(length=150), nullable=True),
    sa.Column('guest_name', sa.String(length=100), nullable=True),
    sa.Column('guest_language', sa.String(length=10), nullable=True),
    sa.Column('check_in', sa.Date(), nullable=False),
    sa.Column('check_out', sa.Date(), nullable=False),
    sa.Column('booked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reservation_status', sa.Enum('PENDING', 'CONFIRMED', 'MODIFIED', 'CANCELLED', 'COMPLETED', name='reservation_status_enum'), server_default=sa.text("'CONFIRMED'"), nullable=False),
    sa.Column('refund_status', sa.Enum('NONE', 'PARTIAL', 'FULL', name='refund_status_enum'), server_default=sa.text("'NONE'"), nullable=False),
    sa.Column('financial_status', sa.Enum('ESTIMATED', 'CONFIRMED', 'MANUALLY_ADJUSTED', name='financial_status_enum'), server_default=sa.text("'ESTIMATED'"), nullable=False),
    sa.Column('gross_amount', sa.Integer(), nullable=True),
    sa.Column('fee_amount', sa.Integer(), nullable=True),
    sa.Column('net_amount', sa.Integer(), nullable=True),
    sa.Column('expected_settlement_at', sa.Date(), nullable=True),
    sa.Column('actual_settlement_at', sa.Date(), nullable=True),
    sa.Column('host_confirmation_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    postgresql.ExcludeConstraint((sa.column('bed_id'), '='), (sa.text('tsrange(check_in::timestamp, check_out::timestamp)'), '&&'), where=sa.text("bed_id IS NOT NULL AND reservation_status IN ('CONFIRMED', 'MODIFIED')"), using='gist', name='excl_bed_overlap'),
    postgresql.ExcludeConstraint((sa.column('property_id'), '='), (sa.text('tsrange(check_in::timestamp, check_out::timestamp)'), '&&'), where=sa.text("room_id IS NULL AND bed_id IS NULL AND reservation_status IN ('CONFIRMED', 'MODIFIED')"), using='gist', name='excl_property_overlap'),
    postgresql.ExcludeConstraint((sa.column('room_id'), '='), (sa.text('tsrange(check_in::timestamp, check_out::timestamp)'), '&&'), where=sa.text("room_id IS NOT NULL AND bed_id IS NULL AND reservation_status IN ('CONFIRMED', 'MODIFIED')"), using='gist', name='excl_room_overlap'),
    sa.CheckConstraint('(room_id IS NULL AND bed_id IS NULL) OR (room_id IS NOT NULL AND bed_id IS NULL) OR (room_id IS NOT NULL AND bed_id IS NOT NULL)', name='ck_reservations_unit_shape'),
    sa.CheckConstraint('check_out > check_in', name='ck_reservations_date_order'),
    sa.ForeignKeyConstraint(['bed_id', 'room_id'], ['beds.bed_id', 'beds.room_id'], name='fk_reservations_bed_room'),
    sa.ForeignKeyConstraint(['channel_connection_id', 'property_id'], ['channel_connections.connection_id', 'channel_connections.property_id'], name='fk_reservations_channel_property'),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id', 'property_id'], ['rooms.room_id', 'rooms.property_id'], name='fk_reservations_room_property'),
    sa.PrimaryKeyConstraint('reservation_id'),
    sa.UniqueConstraint('channel_connection_id', 'external_uid', name='uq_reservation_channel_uid'),
    sa.UniqueConstraint('reservation_id', 'property_id', name='uq_reservation_property_ref')
    )
    op.create_index('idx_reservations_bed', 'reservations', ['bed_id'], unique=False)
    op.create_index('idx_reservations_channel', 'reservations', ['channel_connection_id'], unique=False)
    op.create_index('idx_reservations_dates', 'reservations', ['property_id', 'check_in', 'check_out'], unique=False)
    op.create_index('idx_reservations_property', 'reservations', ['property_id'], unique=False)
    op.create_index('idx_reservations_room', 'reservations', ['room_id'], unique=False)
    op.create_table('action_items',
    sa.Column('action_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('reservation_id', sa.BigInteger(), nullable=True),
    sa.Column('risk_level', sa.Enum('RED_NOW', 'YELLOW_TODAY', 'GREEN_AUTO', name='action_risk_level_enum'), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'RESOLVED', 'AUTO_RESOLVED', name='action_status_enum'), server_default=sa.text("'OPEN'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id', 'property_id'], ['reservations.reservation_id', 'reservations.property_id'], name='fk_action_items_reservation_property', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index('idx_action_items_property_status', 'action_items', ['property_id', 'status', 'risk_level'], unique=False)
    # --- 수동 추가 2: ACTION_ITEMS 복합FK를 PostgreSQL 15+ 컬럼목록 SET NULL로 교체 ---
    #   autogenerate는 표준 `ON DELETE SET NULL`만 생성한다(SQLAlchemy 2.0이
    #   컬럼목록 문법을 렌더링하지 못함). 그대로 두면 예약 삭제 시 NOT NULL인
    #   property_id까지 NULL로 만들려다 **삭제 자체가 실패**한다(명세서 2.15절).
    op.execute(
        "ALTER TABLE action_items "
        "DROP CONSTRAINT fk_action_items_reservation_property, "
        "ADD CONSTRAINT fk_action_items_reservation_property "
        "FOREIGN KEY (reservation_id, property_id) "
        "REFERENCES reservations (reservation_id, property_id) "
        "ON DELETE SET NULL (reservation_id)"
    )
    op.create_table('cleaning_tasks',
    sa.Column('task_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.BigInteger(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('task_status', sa.Enum('PENDING', 'ASSIGNED', 'IN_PROGRESS', 'COMPLETED', 'VERIFIED', 'ISSUE', name='task_status_enum'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('cleaner_name', sa.String(length=100), nullable=True),
    sa.Column('amenity_shortage', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo_urls', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reservation_id', 'property_id'], ['reservations.reservation_id', 'reservations.property_id'], name='fk_cleaning_tasks_reservation_property', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('reservation_id')
    )
    op.create_index('idx_cleaning_tasks_property_status', 'cleaning_tasks', ['property_id', 'task_status'], unique=False)
    op.create_table('inquiries',
    sa.Column('inquiry_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reservation_id', sa.BigInteger(), nullable=True),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=30), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.property_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reservation_id', 'property_id'], ['reservations.reservation_id', 'reservations.property_id'], name='fk_inquiries_reservation_property', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inquiry_id')
    )
    op.create_index('idx_inquiries_property', 'inquiries', ['property_id'], unique=False)
    op.create_index('idx_inquiries_reservation', 'inquiries', ['reservation_id'], unique=False)
    op.create_table('inquiry_classifications',
    sa.Column('classification_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inquiry_id', sa.BigInteger(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='inquiry_risk_level_enum'), nullable=False),
    sa.Column('auto_respondable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.inquiry_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('classification_id'),
    sa.UniqueConstraint('inquiry_id')
    )
    op.create_table('inquiry_responses',
    sa.Column('response_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('inquiry_id', sa.BigInteger(), nullable=False),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('is_latest', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.inquiry_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('response_id')
    )
    op.create_index('idx_inquiry_responses_inquiry', 'inquiry_responses', ['inquiry_id'], unique=False)
    op.create_index('uniq_inquiry_latest_response', 'inquiry_responses', ['inquiry_id'], unique=True, postgresql_where=sa.text('is_latest = true'))
    op.create_table('inquiry_approvals',
    sa.Column('approval_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('response_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='approval_status_enum'), server_default=sa.text("'PENDING'"), nullable=False),
    sa.Column('approved_by', sa.BigInteger(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['hosts.host_id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['inquiry_responses.response_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index('idx_inquiry_approvals_response', 'inquiry_approvals', ['response_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_inquiry_approvals_response', table_name='inquiry_approvals')
    op.drop_table('inquiry_approvals')
    op.drop_index('uniq_inquiry_latest_response', table_name='inquiry_responses', postgresql_where=sa.text('is_latest = true'))
    op.drop_index('idx_inquiry_responses_inquiry', table_name='inquiry_responses')
    op.drop_table('inquiry_responses')
    op.drop_table('inquiry_classifications')
    op.drop_index('idx_inquiries_reservation', table_name='inquiries')
    op.drop_index('idx_inquiries_property', table_name='inquiries')
    op.drop_table('inquiries')
    op.drop_index('idx_cleaning_tasks_property_status', table_name='cleaning_tasks')
    op.drop_table('cleaning_tasks')
    op.drop_index('idx_action_items_property_status', table_name='action_items')
    op.drop_table('action_items')
    op.drop_index('idx_reservations_room', table_name='reservations')
    op.drop_index('idx_reservations_property', table_name='reservations')
    op.drop_index('idx_reservations_dates', table_name='reservations')
    op.drop_index('idx_reservations_channel', table_name='reservations')
    op.drop_index('idx_reservations_bed', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index('idx_beds_room', table_name='beds')
    op.drop_table('beds')
    op.drop_index('idx_rooms_property', table_name='rooms')
    op.drop_table('rooms')
    op.drop_table('monthly_settlements')
    op.drop_index('idx_knowledge_chunks_property', table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
    op.drop_table('financial_configs')
    op.drop_index('idx_checklist_items_property', table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index('idx_channel_connections_property', table_name='channel_connections')
    op.drop_table('channel_connections')
    op.drop_index('idx_properties_host', table_name='properties')
    op.drop_table('properties')
    op.drop_table('hosts')
    # ### end Alembic commands ###

    # --- 수동 추가 3: ENUM 타입 정리 ---
    #   테이블만 지우면 타입이 남아 다시 upgrade할 때 "type already exists"로
    #   실패한다. 확장(btree_gist/vector)은 다른 스키마가 함께 쓸 수 있으므로
    #   여기서 DROP하지 않는다.
    for type_name in ENUM_TYPE_NAMES:
        op.execute(f"DROP TYPE IF EXISTS {type_name}")
